version: '3.8'

services:
  zlmediakit:
    image: ${REGISTRY}/zlmediakit:${ZLM_TAG}
    container_name: zlmediakit
    ports:
      - "8089:8089"
      - "554:554"
      - "8449:8449"
    volumes:
      - /data/agi7/tinynvr/auth:/opt/media/auth
      - /data/agi7/zlmediakit/log:/opt/media/bin/log
      - /data/mergefs/pool/data/agi7/zlmediakit/record:/opt/media/bin/www/record:rslave
    restart: unless-stopped
