version: '3.8'

services:
  zlmediakit:
    image: ${REGISTRY}/zlmediakit:${ZLM_TAG}
    container_name: zlmediakit
    network_mode: host
    environment:
      MEDIA_CONFIG_TYPE: ${MEDIA_CONFIG_TYPE:-media}
      MEDIA_SERVICE_HOOK_BASE_URL: ${MEDIA_SERVICE_HOOK_BASE_URL:?MEDIA_SERVICE_HOOK_BASE_URL is required}
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
    ports:
      - "8089:8089"
      - "554:554"
      - "8449:8449"
    volumes:
      - /data/agi7/tinynvr/auth:/opt/media/auth
      - /data/agi7/zlmediakit/log:/opt/media/bin/log
      - /data/mergefs:/data/mergefs:rslave
    restart: unless-stopped
