version: '3.8'

services:
  zlmediakit:
    image: ${IMAGES_REGISTRY}/zlmediakit:${ZLM_IMAGE_TAG:-latest}
    container_name: zlmediakit
    network_mode: host
    ports:
      - "8089:8089"
      - "8449:8449"
      - "554:554"
      - "1935:1935"
      - "10000:10000"
      - "10000:10000/udp"
      - "8000:8000/udp"
      - "9000:9000/udp"
    volumes:
      - /data/agi7/zlmediakit/config:/opt/media/conf
      - /data/agi7/zlmediakit/auth:/opt/media/auth
      - /data/agi7/zlmediakit/log:/opt/media/bin/log
      - /data/agi7/zlmediakit/record:/opt/media/bin/www
    restart: unless-stopped
